//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class bdg_Rate
    {
        public int Id { get; set; }
        public int IdShipOwnerCurrencyBaseYear { get; set; }
        public int IdCurrency { get; set; }
        public int Month { get; set; }
        public Nullable<decimal> Value { get; set; }
    
        public virtual bdg_Currency bdg_Currency { get; set; }
        public virtual bdg_ShipOwnerCurrencyBaseYear bdg_ShipOwnerCurrencyBaseYear { get; set; }
    }
}
