//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class bdg_BudgetPlanItem
    {
        public int Id { get; set; }
        public int IdBudgetPlan { get; set; }
        public int IdBudgetItem { get; set; }
        public Nullable<int> IdSupplier { get; set; }
        public string Target { get; set; }
        public int Month { get; set; }
        public int State { get; set; }
        public decimal Summ { get; set; }
        public string Note { get; set; }
    
        public virtual bdg_BudgetItem bdg_BudgetItem { get; set; }
        public virtual bdg_BudgetPlan bdg_BudgetPlan { get; set; }
        public virtual bdg_Supplier bdg_Supplier { get; set; }
    }
}
