//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class bdg_BudgetPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bdg_BudgetPlan()
        {
            this.bdg_BudgetPlanItem = new HashSet<bdg_BudgetPlanItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdShip { get; set; }
        public int State { get; set; }
        public int IdShipOwnerCurrencyBaseYear { get; set; }
        public Nullable<int> ClosedMonth { get; set; }
    
        public virtual C_Ship C_Ship { get; set; }
        public virtual bdg_ShipOwnerCurrencyBaseYear bdg_ShipOwnerCurrencyBaseYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bdg_BudgetPlanItem> bdg_BudgetPlanItem { get; set; }
    }
}
