//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class bdg_BudgetItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bdg_BudgetItem()
        {
            this.bdg_BudgetItem1 = new HashSet<bdg_BudgetItem>();
            this.bdg_BudgetPlanItem = new HashSet<bdg_BudgetPlanItem>();
            this.bdg_PaidmentPosition = new HashSet<bdg_PaidmentPosition>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdParent { get; set; }
        public Nullable<int> IdShipOwner { get; set; }
        public string Code { get; set; }
        public string Name_RU { get; set; }
        public string Name_EN { get; set; }
        public string Description { get; set; }
        public bool IsInBudgetPlanByDefault { get; set; }
        public bool IsGroupingItem { get; set; }
    
        public virtual C_ShipOwner C_ShipOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bdg_BudgetItem> bdg_BudgetItem1 { get; set; }
        public virtual bdg_BudgetItem bdg_BudgetItem2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bdg_BudgetPlanItem> bdg_BudgetPlanItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bdg_PaidmentPosition> bdg_PaidmentPosition { get; set; }
    }
}
