//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class bdg_PaidmentDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bdg_PaidmentDocument()
        {
            this.bdg_PaidmentPosition = new HashSet<bdg_PaidmentPosition>();
            this.C_FileInfo = new HashSet<C_FileInfo>();
        }
    
        public int Id { get; set; }
        public string Num { get; set; }
        public bool IsUsedVAT { get; set; }
        public int State { get; set; }
        public int IdCurrency { get; set; }
        public Nullable<int> IdShipOwnerCurrencyBaseYear { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<decimal> CurrencyRateOnPaidDate { get; set; }
        public Nullable<int> IdExecutorCompany { get; set; }
        public Nullable<int> IdSupplier { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public Nullable<System.DateTime> SendPayerDate { get; set; }
        public string Seller { get; set; }
        public string Discriminator { get; set; }
    
        public virtual C_Person C_Person { get; set; }
        public virtual bdg_Currency bdg_Currency { get; set; }
        public virtual bdg_ShipOwnerCurrencyBaseYear bdg_ShipOwnerCurrencyBaseYear { get; set; }
        public virtual bdg_Supplier bdg_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bdg_PaidmentPosition> bdg_PaidmentPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_FileInfo> C_FileInfo { get; set; }
    }
}
