//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class bdg_PaidmentPosition
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public decimal Summ { get; set; }
        public decimal VATSumm { get; set; }
        public decimal SummWithoutVAT { get; set; }
        public int PlanMonth { get; set; }
        public Nullable<int> VAT { get; set; }
        public Nullable<int> IdShip { get; set; }
        public int IdBudgetItem { get; set; }
        public int IdPaidmentDocument { get; set; }
        public string Discriminator { get; set; }
    
        public virtual C_Ship C_Ship { get; set; }
        public virtual bdg_BudgetItem bdg_BudgetItem { get; set; }
        public virtual bdg_PaidmentDocument bdg_PaidmentDocument { get; set; }
    }
}
