//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class bdg_Currency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bdg_Currency()
        {
            this.bdg_PaidmentDocument = new HashSet<bdg_PaidmentDocument>();
            this.bdg_Rate = new HashSet<bdg_Rate>();
            this.bdg_ShipOwnerCurrencyBaseYear = new HashSet<bdg_ShipOwnerCurrencyBaseYear>();
            this.pms_RepairList = new HashSet<pms_RepairList>();
            this.pms_TRepairList = new HashSet<pms_TRepairList>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public bool VAT { get; set; }
        public Nullable<int> VATValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bdg_PaidmentDocument> bdg_PaidmentDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bdg_Rate> bdg_Rate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bdg_ShipOwnerCurrencyBaseYear> bdg_ShipOwnerCurrencyBaseYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RepairList> pms_RepairList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TRepairList> pms_TRepairList { get; set; }
    }
}
