//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class bdg_ShipOwnerCurrencyBaseYear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bdg_ShipOwnerCurrencyBaseYear()
        {
            this.bdg_BudgetPlan = new HashSet<bdg_BudgetPlan>();
            this.bdg_PaidmentDocument = new HashSet<bdg_PaidmentDocument>();
            this.bdg_Rate = new HashSet<bdg_Rate>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdShipOwner { get; set; }
        public int IdCurrency { get; set; }
        public int Year { get; set; }
        public bool IsExcludingVAT { get; set; }
    
        public virtual C_ShipOwner C_ShipOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bdg_BudgetPlan> bdg_BudgetPlan { get; set; }
        public virtual bdg_Currency bdg_Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bdg_PaidmentDocument> bdg_PaidmentDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bdg_Rate> bdg_Rate { get; set; }
    }
}
