//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ADESettings
    {
        public int Id { get; set; }
        public string ComputerName { get; set; }
        public string ServerPath { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool UseExportToServer { get; set; }
        public Nullable<int> MaxSizeForExportPackage { get; set; }
        public Nullable<int> MaxSizeForAllExportPackage { get; set; }
        public int CheckDataForExportPeriod { get; set; }
        public int CheckPackageForImportPeriod { get; set; }
        public bool UseImportFromServer { get; set; }
        public Nullable<int> MaxSizeForImportPackage { get; set; }
        public Nullable<int> MaxSizeForAllImportPackage { get; set; }
        public Nullable<System.DateTime> LastCheckPackageForDownload { get; set; }
        public Nullable<System.DateTime> LastCheckDataForExport { get; set; }
        public Nullable<System.DateTime> LastCheckPackageForImport { get; set; }
        public bool NoFileExport { get; set; }
        public int ExportMode { get; set; }
        public int ExportFrom { get; set; }
        public int ExportTill { get; set; }
        public bool UseServerDataExchange { get; set; }
        public int ImportMode { get; set; }
        public bool UseImportFromFolder { get; set; }
        public int ImportFrom { get; set; }
        public int ImportTill { get; set; }
    }
}
