//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AttachedFileInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_AttachedFileInfo()
        {
            this.C_Ship_File = new HashSet<C_Ship_File>();
        }
    
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public Nullable<int> FileSize { get; set; }
        public int IdFile { get; set; }
        public string FileExtension { get; set; }
    
        public virtual C_AttachedFile C_AttachedFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Ship_File> C_Ship_File { get; set; }
    }
}
