//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ChangeInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_ChangeInfo()
        {
            this.C_Country = new HashSet<C_Country>();
            this.C_Person = new HashSet<C_Person>();
            this.C_PersonServiceTime = new HashSet<C_PersonServiceTime>();
            this.C_Rank = new HashSet<C_Rank>();
            this.C_ShipSetting = new HashSet<C_ShipSetting>();
            this.C_ShipType = new HashSet<C_ShipType>();
            this.dms_Document = new HashSet<dms_Document>();
            this.dms_DocumentTitle = new HashSet<dms_DocumentTitle>();
            this.dms_FileInfo = new HashSet<dms_FileInfo>();
            this.dms_FileInfo1 = new HashSet<dms_FileInfo>();
            this.dms_Partition = new HashSet<dms_Partition>();
            this.dms_smsChangeDocument = new HashSet<dms_smsChangeDocument>();
            this.dms_smsDocument = new HashSet<dms_smsDocument>();
            this.dms_smsDocument_Ship_NotVisible = new HashSet<dms_smsDocument_Ship_NotVisible>();
            this.dms_smsPartition = new HashSet<dms_smsPartition>();
            this.hseq_Inspection = new HashSet<hseq_Inspection>();
            this.hseq_InspectionName = new HashSet<hseq_InspectionName>();
            this.hseq_Inspector = new HashSet<hseq_Inspector>();
            this.hseq_Observation = new HashSet<hseq_Observation>();
            this.mrv_FuelOperation = new HashSet<mrv_FuelOperation>();
            this.mrv_FuelOperationQuantity = new HashSet<mrv_FuelOperationQuantity>();
            this.mrv_FuelType = new HashSet<mrv_FuelType>();
            this.mrv_FuelType_Ship = new HashSet<mrv_FuelType_Ship>();
            this.mrv_FuelType_VoyagePeriod = new HashSet<mrv_FuelType_VoyagePeriod>();
            this.mrv_Port = new HashSet<mrv_Port>();
            this.mrv_Report_EmissionSource = new HashSet<mrv_Report_EmissionSource>();
            this.mrv_Voyage = new HashSet<mrv_Voyage>();
            this.mrv_VoyagePeriod = new HashSet<mrv_VoyagePeriod>();
            this.pms_SpareLib = new HashSet<pms_SpareLib>();
            this.pms_CodeTMK = new HashSet<pms_CodeTMK>();
            this.pms_CompanySetting = new HashSet<pms_CompanySetting>();
            this.pms_Counter = new HashSet<pms_Counter>();
            this.pms_CounterLogRecord = new HashSet<pms_CounterLogRecord>();
            this.pms_CounterType = new HashSet<pms_CounterType>();
            this.pms_FileInfo = new HashSet<pms_FileInfo>();
            this.pms_FileInfo1 = new HashSet<pms_FileInfo>();
            this.pms_FileInfo_Ship = new HashSet<pms_FileInfo_Ship>();
            this.pms_FileInfoManagedByShip = new HashSet<pms_FileInfoManagedByShip>();
            this.pms_FileInfoManagedByShip1 = new HashSet<pms_FileInfoManagedByShip>();
            this.pms_FileLibInfo = new HashSet<pms_FileLibInfo>();
            this.pms_FileLibInfo1 = new HashSet<pms_FileLibInfo>();
            this.pms_InnerCompanySetting = new HashSet<pms_InnerCompanySetting>();
            this.pms_Job_File = new HashSet<pms_Job_File>();
            this.pms_Job = new HashSet<pms_Job>();
            this.pms_Job_Spare = new HashSet<pms_Job_Spare>();
            this.pms_JobHistoryRecord = new HashSet<pms_JobHistoryRecord>();
            this.pms_JobOrderItem = new HashSet<pms_JobOrderItem>();
            this.pms_JobOrderItem_InnerInfo = new HashSet<pms_JobOrderItem_InnerInfo>();
            this.pms_JobPeriod = new HashSet<pms_JobPeriod>();
            this.pms_JobPlan = new HashSet<pms_JobPlan>();
            this.pms_JobStatisticSetting = new HashSet<pms_JobStatisticSetting>();
            this.pms_JobType = new HashSet<pms_JobType>();
            this.pms_MaterialCatalogue = new HashSet<pms_MaterialCatalogue>();
            this.pms_MaterialCatalogueSection = new HashSet<pms_MaterialCatalogueSection>();
            this.pms_Object_File = new HashSet<pms_Object_File>();
            this.pms_Object = new HashSet<pms_Object>();
            this.pms_Object_Counter = new HashSet<pms_Object_Counter>();
            this.pms_Object_Spare = new HashSet<pms_Object_Spare>();
            this.pms_OperatingTime = new HashSet<pms_OperatingTime>();
            this.pms_Partition = new HashSet<pms_Partition>();
            this.pms_RepairList = new HashSet<pms_RepairList>();
            this.pms_RepairListApprovalStage = new HashSet<pms_RepairListApprovalStage>();
            this.pms_RepairListApproveTable = new HashSet<pms_RepairListApproveTable>();
            this.pms_RepairListItem = new HashSet<pms_RepairListItem>();
            this.pms_RepairListPartition = new HashSet<pms_RepairListPartition>();
            this.pms_RepairListRank = new HashSet<pms_RepairListRank>();
            this.pms_RepairListSpare = new HashSet<pms_RepairListSpare>();
            this.pms_RepairListMeasureUnit = new HashSet<pms_RepairListMeasureUnit>();
            this.pms_RepairPlan = new HashSet<pms_RepairPlan>();
            this.pms_RepairPlanRepairType = new HashSet<pms_RepairPlanRepairType>();
            this.pms_RepairPlanTableManage = new HashSet<pms_RepairPlanTableManage>();
            this.pms_Requisition = new HashSet<pms_Requisition>();
            this.pms_Requisition_InnerInfo = new HashSet<pms_Requisition_InnerInfo>();
            this.pms_RequisitionDepartment = new HashSet<pms_RequisitionDepartment>();
            this.pms_RequisitionDestination = new HashSet<pms_RequisitionDestination>();
            this.pms_RequisitionType = new HashSet<pms_RequisitionType>();
            this.pms_SFI = new HashSet<pms_SFI>();
            this.pms_FileInfo_Ship1 = new HashSet<pms_FileInfo_Ship>();
            this.pms_Spare_File = new HashSet<pms_Spare_File>();
            this.pms_Spare_Ship = new HashSet<pms_Spare_Ship>();
            this.pms_SpareManufacturerCatalog = new HashSet<pms_SpareManufacturerCatalog>();
            this.pms_SpareOrderItem = new HashSet<pms_SpareOrderItem>();
            this.pms_SpareOrderItem_InnerInfo = new HashSet<pms_SpareOrderItem_InnerInfo>();
            this.pms_StoreInventoryRecord = new HashSet<pms_StoreInventoryRecord>();
            this.pms_StoreItem = new HashSet<pms_StoreItem>();
            this.pms_StoreLocation = new HashSet<pms_StoreLocation>();
            this.pms_StoreSection = new HashSet<pms_StoreSection>();
            this.pms_TechPlace = new HashSet<pms_TechPlace>();
            this.pms_TJob_File = new HashSet<pms_TJob_File>();
            this.pms_TJob = new HashSet<pms_TJob>();
            this.pms_TJob_Spare = new HashSet<pms_TJob_Spare>();
            this.pms_TJobPeriod = new HashSet<pms_TJobPeriod>();
            this.pms_TObject_File = new HashSet<pms_TObject_File>();
            this.pms_TObject = new HashSet<pms_TObject>();
            this.pms_TObject_Spare = new HashSet<pms_TObject_Spare>();
            this.pms_TRepairList = new HashSet<pms_TRepairList>();
            this.pms_TRepairListItem = new HashSet<pms_TRepairListItem>();
            this.pms_TRepairListSpare = new HashSet<pms_TRepairListSpare>();
            this.pms_SpareLib_File = new HashSet<pms_SpareLib_File>();
            this.prs_CheckList = new HashSet<prs_CheckList>();
            this.prs_CheckListItem = new HashSet<prs_CheckListItem>();
            this.prs_DocumentType = new HashSet<prs_DocumentType>();
            this.prs_PersonCard = new HashSet<prs_PersonCard>();
            this.prs_PersonCard_InnerInfo = new HashSet<prs_PersonCard_InnerInfo>();
            this.prs_PersonCard_ShipType = new HashSet<prs_PersonCard_ShipType>();
            this.prs_PersonContract = new HashSet<prs_PersonContract>();
            this.prs_PersonDocument = new HashSet<prs_PersonDocument>();
            this.prs_Qualification = new HashSet<prs_Qualification>();
        }
    
        public int Id { get; set; }
        public int State { get; set; }
        public bool IsNotUsed { get; set; }
        public bool HasProposeItemOnModify { get; set; }
        public bool IsOldCopyNonEmpty { get; set; }
        public bool WasAddedByLastImport { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<System.DateTime> ModifyDateOuter { get; set; }
        public string UserOuter { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> IdUserCreator { get; set; }
        public string UserOuterCreator { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public Nullable<int> IdPackageLastImport { get; set; }
        public Nullable<int> IdPackageLastExport { get; set; }
        public Nullable<System.Guid> ExportCode { get; set; }
    
        public virtual C_ExportImportInfo C_ExportImportInfo { get; set; }
        public virtual C_ExportImportInfo C_ExportImportInfo1 { get; set; }
        public virtual C_User C_User { get; set; }
        public virtual C_User C_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Country> C_Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Person> C_Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_PersonServiceTime> C_PersonServiceTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Rank> C_Rank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ShipSetting> C_ShipSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ShipType> C_ShipType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_Document> dms_Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_DocumentTitle> dms_DocumentTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_FileInfo> dms_FileInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_FileInfo> dms_FileInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_Partition> dms_Partition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_smsChangeDocument> dms_smsChangeDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_smsDocument> dms_smsDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_smsDocument_Ship_NotVisible> dms_smsDocument_Ship_NotVisible { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_smsPartition> dms_smsPartition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hseq_Inspection> hseq_Inspection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hseq_InspectionName> hseq_InspectionName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hseq_Inspector> hseq_Inspector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hseq_Observation> hseq_Observation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mrv_FuelOperation> mrv_FuelOperation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mrv_FuelOperationQuantity> mrv_FuelOperationQuantity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mrv_FuelType> mrv_FuelType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mrv_FuelType_Ship> mrv_FuelType_Ship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mrv_FuelType_VoyagePeriod> mrv_FuelType_VoyagePeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mrv_Port> mrv_Port { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mrv_Report_EmissionSource> mrv_Report_EmissionSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mrv_Voyage> mrv_Voyage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mrv_VoyagePeriod> mrv_VoyagePeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_SpareLib> pms_SpareLib { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_CodeTMK> pms_CodeTMK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_CompanySetting> pms_CompanySetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Counter> pms_Counter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_CounterLogRecord> pms_CounterLogRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_CounterType> pms_CounterType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_FileInfo> pms_FileInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_FileInfo> pms_FileInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_FileInfo_Ship> pms_FileInfo_Ship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_FileInfoManagedByShip> pms_FileInfoManagedByShip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_FileInfoManagedByShip> pms_FileInfoManagedByShip1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_FileLibInfo> pms_FileLibInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_FileLibInfo> pms_FileLibInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_InnerCompanySetting> pms_InnerCompanySetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Job_File> pms_Job_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Job> pms_Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Job_Spare> pms_Job_Spare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobHistoryRecord> pms_JobHistoryRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobOrderItem> pms_JobOrderItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobOrderItem_InnerInfo> pms_JobOrderItem_InnerInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobPeriod> pms_JobPeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobPlan> pms_JobPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobStatisticSetting> pms_JobStatisticSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobType> pms_JobType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_MaterialCatalogue> pms_MaterialCatalogue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_MaterialCatalogueSection> pms_MaterialCatalogueSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Object_File> pms_Object_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Object> pms_Object { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Object_Counter> pms_Object_Counter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Object_Spare> pms_Object_Spare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_OperatingTime> pms_OperatingTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Partition> pms_Partition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RepairList> pms_RepairList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RepairListApprovalStage> pms_RepairListApprovalStage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RepairListApproveTable> pms_RepairListApproveTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RepairListItem> pms_RepairListItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RepairListPartition> pms_RepairListPartition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RepairListRank> pms_RepairListRank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RepairListSpare> pms_RepairListSpare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RepairListMeasureUnit> pms_RepairListMeasureUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RepairPlan> pms_RepairPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RepairPlanRepairType> pms_RepairPlanRepairType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RepairPlanTableManage> pms_RepairPlanTableManage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Requisition> pms_Requisition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Requisition_InnerInfo> pms_Requisition_InnerInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RequisitionDepartment> pms_RequisitionDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RequisitionDestination> pms_RequisitionDestination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RequisitionType> pms_RequisitionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_SFI> pms_SFI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_FileInfo_Ship> pms_FileInfo_Ship1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Spare_File> pms_Spare_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Spare_Ship> pms_Spare_Ship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_SpareManufacturerCatalog> pms_SpareManufacturerCatalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_SpareOrderItem> pms_SpareOrderItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_SpareOrderItem_InnerInfo> pms_SpareOrderItem_InnerInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_StoreInventoryRecord> pms_StoreInventoryRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_StoreItem> pms_StoreItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_StoreLocation> pms_StoreLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_StoreSection> pms_StoreSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TechPlace> pms_TechPlace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TJob_File> pms_TJob_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TJob> pms_TJob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TJob_Spare> pms_TJob_Spare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TJobPeriod> pms_TJobPeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TObject_File> pms_TObject_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TObject> pms_TObject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TObject_Spare> pms_TObject_Spare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TRepairList> pms_TRepairList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TRepairListItem> pms_TRepairListItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TRepairListSpare> pms_TRepairListSpare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_SpareLib_File> pms_SpareLib_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prs_CheckList> prs_CheckList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prs_CheckListItem> prs_CheckListItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prs_DocumentType> prs_DocumentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prs_PersonCard> prs_PersonCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prs_PersonCard_InnerInfo> prs_PersonCard_InnerInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prs_PersonCard_ShipType> prs_PersonCard_ShipType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prs_PersonContract> prs_PersonContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prs_PersonDocument> prs_PersonDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prs_Qualification> prs_Qualification { get; set; }
    }
}
