//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ExportImportStepStatistic
    {
        public int Id { get; set; }
        public int Step { get; set; }
        public Nullable<int> NumberProcessed { get; set; }
        public int NumberInPackage { get; set; }
        public int IdExportImportInfo { get; set; }
    
        public virtual C_ExportImportInfo C_ExportImportInfo { get; set; }
    }
}
