//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_FileInfo
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public Nullable<int> FileSize { get; set; }
        public int IdFileData { get; set; }
        public string FileExtension { get; set; }
    
        public virtual C_FileData C_FileData { get; set; }
        public virtual bdg_PaidmentDocument bdg_PaidmentDocument { get; set; }
        public virtual bdg_Supplier bdg_Supplier { get; set; }
    }
}
