//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Person()
        {
            this.C_PersonServiceTime = new HashSet<C_PersonServiceTime>();
            this.bdg_PaidmentDocument = new HashSet<bdg_PaidmentDocument>();
            this.hseq_Observation = new HashSet<hseq_Observation>();
            this.pms_Access = new HashSet<pms_Access>();
            this.pms_JobHistoryRecord = new HashSet<pms_JobHistoryRecord>();
            this.pms_TechPlace = new HashSet<pms_TechPlace>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdShip { get; set; }
        public string Name { get; set; }
        public int IdRank { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
        public bool IsWatchkeeper { get; set; }
        public Nullable<int> IdRequisitionRank { get; set; }
        public Nullable<int> IdRepairListRank { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual C_Rank C_Rank { get; set; }
        public virtual C_Ship C_Ship { get; set; }
        public virtual pms_RepairListRank pms_RepairListRank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_PersonServiceTime> C_PersonServiceTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bdg_PaidmentDocument> bdg_PaidmentDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hseq_Observation> hseq_Observation { get; set; }
        public virtual pms_RequisitionRank pms_RequisitionRank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Access> pms_Access { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobHistoryRecord> pms_JobHistoryRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TechPlace> pms_TechPlace { get; set; }
    }
}
