//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ShipSetting
    {
        public int Id { get; set; }
        public Nullable<int> IdShip { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
        public int UnitOfCargo { get; set; }
        public Nullable<decimal> AuxiliaryEnginesPower { get; set; }
        public Nullable<decimal> MainEnginesPower { get; set; }
        public Nullable<decimal> NetCapacity { get; set; }
        public Nullable<decimal> GrossTonnage { get; set; }
        public Nullable<decimal> DWT { get; set; }
        public Nullable<decimal> EIV { get; set; }
        public Nullable<decimal> EEDI { get; set; }
        public string ShipOwnerName { get; set; }
        public string ShipOwnerAddress { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string ContactName { get; set; }
        public string ContactAddress { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<int> ControlEFMethod { get; set; }
        public string IceClass { get; set; }
        public string TechPerformanceIndicator { get; set; }
        public string PortRegistry { get; set; }
        public Nullable<int> IdShipType { get; set; }
        public Nullable<int> IdCountry { get; set; }
        public string Callsign { get; set; }
        public Nullable<int> ShipProjectId { get; set; }
        public string PlaceBuild { get; set; }
        public string ClassShip { get; set; }
        public Nullable<decimal> OverallLength { get; set; }
        public Nullable<decimal> LengthPerpendicular { get; set; }
        public Nullable<decimal> WidthShip { get; set; }
        public Nullable<decimal> BoardHeight { get; set; }
        public Nullable<decimal> DraftSummerMark { get; set; }
        public Nullable<decimal> DockWeight { get; set; }
        public string OperatorName { get; set; }
        public string OperatorAddress { get; set; }
        public string OperatorNameIsmc { get; set; }
        public string OperatorAddressIsmc { get; set; }
        public string Captain { get; set; }
        public string СhiefMechanicalEngineer { get; set; }
        public string ProjectNumber { get; set; }
        public string PlantBuilder { get; set; }
        public Nullable<int> QuantityMainEngine { get; set; }
        public string BrandMainEngine { get; set; }
        public Nullable<int> QuantityAuxEngine { get; set; }
        public string BrandAuxEngine { get; set; }
        public Nullable<decimal> DraftStern { get; set; }
        public Nullable<decimal> DisplacementFull { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual C_Country C_Country { get; set; }
        public virtual C_Ship C_Ship { get; set; }
        public virtual C_ShipProject C_ShipProject { get; set; }
        public virtual C_ShipType C_ShipType { get; set; }
    }
}
