//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ShipStatus
    {
        public int Id { get; set; }
        public Nullable<int> ShipId { get; set; }
        public int ShipUsage { get; set; }
        public string Location { get; set; }
        public string CurrentWork { get; set; }
        public string CurrentWorkPlace { get; set; }
        public int WorkTimeOverall { get; set; }
        public int WorkTimeCommercial { get; set; }
        public bool ShorePowerSupplyUsed { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual C_Ship C_Ship { get; set; }
        public virtual C_User C_User { get; set; }
        public virtual C_User C_User1 { get; set; }
    }
}
