//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Ship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Ship()
        {
            this.C_ExportImportInfo = new HashSet<C_ExportImportInfo>();
            this.C_Person = new HashSet<C_Person>();
            this.C_RemoveCommand = new HashSet<C_RemoveCommand>();
            this.C_ShipPropertyValue = new HashSet<C_ShipPropertyValue>();
            this.C_ShipSetting = new HashSet<C_ShipSetting>();
            this.C_ShipStatus = new HashSet<C_ShipStatus>();
            this.bdg_BudgetPlan = new HashSet<bdg_BudgetPlan>();
            this.bdg_PaidmentPosition = new HashSet<bdg_PaidmentPosition>();
            this.dms_Document = new HashSet<dms_Document>();
            this.dms_FileDataExportInfo = new HashSet<dms_FileDataExportInfo>();
            this.dms_smsDocument_Ship_NotVisible = new HashSet<dms_smsDocument_Ship_NotVisible>();
            this.hseq_Inspection = new HashSet<hseq_Inspection>();
            this.hseq_InspectionPlan = new HashSet<hseq_InspectionPlan>();
            this.mrv_FuelOperation = new HashSet<mrv_FuelOperation>();
            this.mrv_FuelType_Ship = new HashSet<mrv_FuelType_Ship>();
            this.mrv_Report_EmissionSource = new HashSet<mrv_Report_EmissionSource>();
            this.mrv_Voyage = new HashSet<mrv_Voyage>();
            this.pms_CodeTMK = new HashSet<pms_CodeTMK>();
            this.pms_Counter = new HashSet<pms_Counter>();
            this.pms_FileDataExportInfo = new HashSet<pms_FileDataExportInfo>();
            this.pms_FileInfoManagedByShip = new HashSet<pms_FileInfoManagedByShip>();
            this.pms_Job = new HashSet<pms_Job>();
            this.pms_Object = new HashSet<pms_Object>();
            this.pms_ProposeItem = new HashSet<pms_ProposeItem>();
            this.pms_RepairList = new HashSet<pms_RepairList>();
            this.pms_RepairListApproveTable = new HashSet<pms_RepairListApproveTable>();
            this.pms_RepairPlan = new HashSet<pms_RepairPlan>();
            this.pms_Requisition = new HashSet<pms_Requisition>();
            this.pms_FileInfo_Ship = new HashSet<pms_FileInfo_Ship>();
            this.pms_Spare_Ship = new HashSet<pms_Spare_Ship>();
            this.pms_StoreInventoryRecord = new HashSet<pms_StoreInventoryRecord>();
            this.pms_StoreLocation = new HashSet<pms_StoreLocation>();
            this.pms_StoreReserve = new HashSet<pms_StoreReserve>();
            this.pms_StoreReserveForJobPlan = new HashSet<pms_StoreReserveForJobPlan>();
            this.pms_StoreSection = new HashSet<pms_StoreSection>();
            this.pms_TechPlace = new HashSet<pms_TechPlace>();
            this.prs_СrewСhangePlan = new HashSet<prs_СrewСhangePlan>();
            this.prs_PersonContract = new HashSet<prs_PersonContract>();
            this.C_Ship_File = new HashSet<C_Ship_File>();
        }
    
        public int IdShip { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public int SortNumber { get; set; }
        public Nullable<int> IdShipGroup { get; set; }
        public bool IsHidden { get; set; }
        public bool IsUseInMarinos { get; set; }
        public int IdShipOwner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ExportImportInfo> C_ExportImportInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Person> C_Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_RemoveCommand> C_RemoveCommand { get; set; }
        public virtual C_ShipGroup C_ShipGroup { get; set; }
        public virtual C_ShipOwner C_ShipOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ShipPropertyValue> C_ShipPropertyValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ShipSetting> C_ShipSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_ShipStatus> C_ShipStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bdg_BudgetPlan> bdg_BudgetPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bdg_PaidmentPosition> bdg_PaidmentPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_Document> dms_Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_FileDataExportInfo> dms_FileDataExportInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_smsDocument_Ship_NotVisible> dms_smsDocument_Ship_NotVisible { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hseq_Inspection> hseq_Inspection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hseq_InspectionPlan> hseq_InspectionPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mrv_FuelOperation> mrv_FuelOperation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mrv_FuelType_Ship> mrv_FuelType_Ship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mrv_Report_EmissionSource> mrv_Report_EmissionSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mrv_Voyage> mrv_Voyage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_CodeTMK> pms_CodeTMK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Counter> pms_Counter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_FileDataExportInfo> pms_FileDataExportInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_FileInfoManagedByShip> pms_FileInfoManagedByShip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Job> pms_Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Object> pms_Object { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_ProposeItem> pms_ProposeItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RepairList> pms_RepairList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RepairListApproveTable> pms_RepairListApproveTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RepairPlan> pms_RepairPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Requisition> pms_Requisition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_FileInfo_Ship> pms_FileInfo_Ship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Spare_Ship> pms_Spare_Ship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_StoreInventoryRecord> pms_StoreInventoryRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_StoreLocation> pms_StoreLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_StoreReserve> pms_StoreReserve { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_StoreReserveForJobPlan> pms_StoreReserveForJobPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_StoreSection> pms_StoreSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TechPlace> pms_TechPlace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prs_СrewСhangePlan> prs_СrewСhangePlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prs_PersonContract> prs_PersonContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Ship_File> C_Ship_File { get; set; }
    }
}
