//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonData
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> UpdatesDate { get; set; }
        public Nullable<bool> UpdatesProgramWorkStatus { get; set; }
        public Nullable<int> ProgramModule { get; set; }
        public int DBVersion { get; set; }
        public int ProgramVersion_1 { get; set; }
        public int ProgramVersion_2 { get; set; }
        public int ProgramVersion_3 { get; set; }
        public int UpdatesPackageNum { get; set; }
        public int CorrectionVersion { get; set; }
    }
}
