//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class dms_smsDocument_Ship_NotVisible
    {
        public int Id { get; set; }
        public Nullable<int> IdSmsDocument { get; set; }
        public Nullable<int> IdShip { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
        public Nullable<int> IdSmsPartition { get; set; }
        public Nullable<int> IdShipOwner { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual C_Ship C_Ship { get; set; }
        public virtual dms_smsDocument dms_smsDocument { get; set; }
        public virtual dms_smsPartition dms_smsPartition { get; set; }
    }
}
