//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class dms_smsDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dms_smsDocument()
        {
            this.dms_smsChangeDocument = new HashSet<dms_smsChangeDocument>();
            this.dms_smsDocument_Ship_NotVisible = new HashSet<dms_smsDocument_Ship_NotVisible>();
            this.dms_smsDocument_File = new HashSet<dms_smsDocument_File>();
        }
    
        public int Id { get; set; }
        public string Name_rus { get; set; }
        public string Name_en { get; set; }
        public string Number { get; set; }
        public int IdSmsPartition { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
        public Nullable<int> NumberPP { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_smsChangeDocument> dms_smsChangeDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_smsDocument_Ship_NotVisible> dms_smsDocument_Ship_NotVisible { get; set; }
        public virtual dms_smsPartition dms_smsPartition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_smsDocument_File> dms_smsDocument_File { get; set; }
    }
}
