//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class dms_FileInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dms_FileInfo()
        {
            this.dms_Document_File = new HashSet<dms_Document_File>();
            this.dms_DocumentTitle_File = new HashSet<dms_DocumentTitle_File>();
            this.dms_FileDataExportInfo = new HashSet<dms_FileDataExportInfo>();
            this.dms_smsDocument_File = new HashSet<dms_smsDocument_File>();
        }
    
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public Nullable<int> FileSize { get; set; }
        public int IdFile { get; set; }
        public int IdChangeInfo { get; set; }
        public string FileExtension { get; set; }
        public int IdChangeInfoFileData { get; set; }
        public Nullable<int> IDOuter { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual C_ChangeInfo C_ChangeInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_Document_File> dms_Document_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_DocumentTitle_File> dms_DocumentTitle_File { get; set; }
        public virtual dms_File dms_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_FileDataExportInfo> dms_FileDataExportInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_smsDocument_File> dms_smsDocument_File { get; set; }
    }
}
