//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class dms_Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dms_Document()
        {
            this.dms_Document_File = new HashSet<dms_Document_File>();
        }
    
        public int Id { get; set; }
        public int IdDocumentTitle { get; set; }
        public Nullable<int> IdShip { get; set; }
        public string NoteByShip { get; set; }
        public Nullable<System.DateTime> DocumentDateByShip { get; set; }
        public Nullable<System.DateTime> ExpUntilDateByShip { get; set; }
        public Nullable<System.DateTime> ConfirmUntilDateByShip { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
        public bool IsActive { get; set; }
        public string NoteByCompany { get; set; }
        public Nullable<System.DateTime> DocumentDateByCompany { get; set; }
        public Nullable<System.DateTime> ExpUntilDateByCompany { get; set; }
        public Nullable<System.DateTime> ConfirmUntilDateByCompany { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual C_Ship C_Ship { get; set; }
        public virtual dms_DocumentTitle dms_DocumentTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_Document_File> dms_Document_File { get; set; }
    }
}
