//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class dms_smsChangeDocument
    {
        public int Id { get; set; }
        public int IdSmsDocument { get; set; }
        public string VersionNumber { get; set; }
        public System.DateTime VersionDate { get; set; }
        public System.DateTime LastDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual dms_smsDocument dms_smsDocument { get; set; }
    }
}
