//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class hseq_Observation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hseq_Observation()
        {
            this.hseq_Observation_File = new HashSet<hseq_Observation_File>();
        }
    
        public int Id { get; set; }
        public int IdInspection { get; set; }
        public int Type { get; set; }
        public string Observation { get; set; }
        public string Reason { get; set; }
        public string CorrectAction { get; set; }
        public string WarningAction { get; set; }
        public Nullable<int> IdPersonInCompany { get; set; }
        public string PersonInCompany { get; set; }
        public Nullable<int> IdRankInShip { get; set; }
        public Nullable<System.DateTime> PerformToDate { get; set; }
        public Nullable<int> Notification { get; set; }
        public bool IsRequiredCompanyAttention { get; set; }
        public bool IsAgreedInCompany { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string CommentByCompany { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual C_Person C_Person { get; set; }
        public virtual C_Rank C_Rank { get; set; }
        public virtual hseq_Inspection hseq_Inspection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hseq_Observation_File> hseq_Observation_File { get; set; }
    }
}
