//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class hseq_Inspection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hseq_Inspection()
        {
            this.hseq_Inspection_File = new HashSet<hseq_Inspection_File>();
            this.hseq_Observation = new HashSet<hseq_Observation>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdShip { get; set; }
        public int State { get; set; }
        public bool IsCreatedByCompany { get; set; }
        public int IdInspectionName { get; set; }
        public Nullable<int> IdInspector { get; set; }
        public string InspectorOther { get; set; }
        public System.DateTime Date { get; set; }
        public string Port { get; set; }
        public string CommentByCompany { get; set; }
        public string CommentByShip { get; set; }
        public Nullable<System.DateTime> PerformToDate { get; set; }
        public Nullable<int> Notification { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual C_Ship C_Ship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hseq_Inspection_File> hseq_Inspection_File { get; set; }
        public virtual hseq_InspectionName hseq_InspectionName { get; set; }
        public virtual hseq_Inspector hseq_Inspector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hseq_Observation> hseq_Observation { get; set; }
    }
}
