//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class mrv_FuelType_VoyagePeriod
    {
        public int Id { get; set; }
        public int IdFuelType { get; set; }
        public int IdVoyagePeriod { get; set; }
        public Nullable<decimal> notused_Consumption { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
        public Nullable<decimal> RemainQuantityEnd { get; set; }
        public decimal RemainQuantityStart { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual mrv_FuelType mrv_FuelType { get; set; }
        public virtual mrv_VoyagePeriod mrv_VoyagePeriod { get; set; }
    }
}
