//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class mrv_FuelOperation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mrv_FuelOperation()
        {
            this.mrv_FuelOperation_File = new HashSet<mrv_FuelOperation_File>();
            this.mrv_FuelOperationQuantity = new HashSet<mrv_FuelOperationQuantity>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdShip { get; set; }
        public System.DateTime DateTime { get; set; }
        public int OperationType { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual C_Ship C_Ship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mrv_FuelOperation_File> mrv_FuelOperation_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mrv_FuelOperationQuantity> mrv_FuelOperationQuantity { get; set; }
    }
}
