//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class mrv_VoyagePeriod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mrv_VoyagePeriod()
        {
            this.mrv_FuelType_VoyagePeriod = new HashSet<mrv_FuelType_VoyagePeriod>();
        }
    
        public int Id { get; set; }
        public int IdVoyage { get; set; }
        public int PeriodType { get; set; }
        public bool IsMRV { get; set; }
        public Nullable<int> IdPortStart { get; set; }
        public string PortStartOther { get; set; }
        public Nullable<bool> IsPortStartOtherEC { get; set; }
        public Nullable<int> IdPortEnd { get; set; }
        public string PortEndOther { get; set; }
        public Nullable<bool> IsPortEndOtherEC { get; set; }
        public System.DateTime DateTimeStart { get; set; }
        public Nullable<System.DateTime> DateTimeEnd { get; set; }
        public string Description_Ship { get; set; }
        public string Description_Company { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public Nullable<decimal> AmountOfCargo { get; set; }
        public Nullable<int> DurationInHours { get; set; }
        public Nullable<decimal> HeatFuel { get; set; }
        public Nullable<decimal> DynamicFuel { get; set; }
        public Nullable<decimal> CargoVolume { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mrv_FuelType_VoyagePeriod> mrv_FuelType_VoyagePeriod { get; set; }
        public virtual mrv_Port mrv_Port { get; set; }
        public virtual mrv_Port mrv_Port1 { get; set; }
        public virtual mrv_Voyage mrv_Voyage { get; set; }
    }
}
