//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_Counter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_Counter()
        {
            this.pms_CounterLogRecord1 = new HashSet<pms_CounterLogRecord>();
            this.pms_JobHistoryCounterRecord = new HashSet<pms_JobHistoryCounterRecord>();
            this.pms_Object_Counter = new HashSet<pms_Object_Counter>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdType { get; set; }
        public Nullable<int> IdShip { get; set; }
        public Nullable<int> IdPartition { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
        public bool IsActive { get; set; }
        public bool IsMain { get; set; }
        public Nullable<int> IdLastCounterLogRecord { get; set; }
        public Nullable<decimal> AverageValuePerMonth { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual C_Ship C_Ship { get; set; }
        public virtual pms_CounterLogRecord pms_CounterLogRecord { get; set; }
        public virtual pms_CounterType pms_CounterType { get; set; }
        public virtual pms_Partition pms_Partition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_CounterLogRecord> pms_CounterLogRecord1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobHistoryCounterRecord> pms_JobHistoryCounterRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Object_Counter> pms_Object_Counter { get; set; }
    }
}
