//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_TRepairListSpare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_TRepairListSpare()
        {
            this.pms_TRepairListSpare_File = new HashSet<pms_TRepairListSpare_File>();
        }
    
        public int Id { get; set; }
        public int TRepairListItemId { get; set; }
        public Nullable<int> IdSpareLib { get; set; }
        public string Name { get; set; }
        public int MeasureUnitId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public int SortOrder { get; set; }
        public string Note { get; set; }
        public string ReqDoc { get; set; }
        public string CatalogueNumber { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual pms_RepairListMeasureUnit pms_RepairListMeasureUnit { get; set; }
        public virtual pms_SpareLib pms_SpareLib { get; set; }
        public virtual pms_TRepairListItem pms_TRepairListItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TRepairListSpare_File> pms_TRepairListSpare_File { get; set; }
    }
}
