//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_JobPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_JobPlan()
        {
            this.pms_JobHistoryRecord = new HashSet<pms_JobHistoryRecord>();
            this.pms_StoreReserveForJobPlan = new HashSet<pms_StoreReserveForJobPlan>();
        }
    
        public int Id { get; set; }
        public int IdJob { get; set; }
        public System.DateTime PlanDate { get; set; }
        public int Result { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
        public Nullable<int> IdJobOrderItem { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<int> IdRank { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual C_Rank C_Rank { get; set; }
        public virtual pms_Job pms_Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobHistoryRecord> pms_JobHistoryRecord { get; set; }
        public virtual pms_JobOrderItem pms_JobOrderItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_StoreReserveForJobPlan> pms_StoreReserveForJobPlan { get; set; }
    }
}
