//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_TObject_Spare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_TObject_Spare()
        {
            this.pms_Object_Spare = new HashSet<pms_Object_Spare>();
        }
    
        public int Id { get; set; }
        public int IdTObject { get; set; }
        public int IdSpareLib { get; set; }
        public decimal RequiredNumber { get; set; }
        public int IdChangeInfo { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Object_Spare> pms_Object_Spare { get; set; }
        public virtual pms_SpareLib pms_SpareLib { get; set; }
        public virtual pms_TObject pms_TObject { get; set; }
    }
}
