//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_SpareReqApprovalStage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_SpareReqApprovalStage()
        {
            this.pms_SpareOrderItem_InnerInfo = new HashSet<pms_SpareOrderItem_InnerInfo>();
            this.pms_SpareReqApprovalStage1 = new HashSet<pms_SpareReqApprovalStage>();
        }
    
        public int Id { get; set; }
        public int Type { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<int> Conditional { get; set; }
        public int IdRequisitionRank { get; set; }
        public Nullable<int> IdParent { get; set; }
    
        public virtual pms_RequisitionRank pms_RequisitionRank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_SpareOrderItem_InnerInfo> pms_SpareOrderItem_InnerInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_SpareReqApprovalStage> pms_SpareReqApprovalStage1 { get; set; }
        public virtual pms_SpareReqApprovalStage pms_SpareReqApprovalStage2 { get; set; }
    }
}
