//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_JobHistoryRecord_File
    {
        public int Id { get; set; }
        public int IdJobHistoryRecord { get; set; }
        public int IdFile { get; set; }
    
        public virtual pms_FileInfoManagedByShip pms_FileInfoManagedByShip { get; set; }
        public virtual pms_JobHistoryRecord pms_JobHistoryRecord { get; set; }
    }
}
