//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_SpareLib
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_SpareLib()
        {
            this.pms_Spare_Ship = new HashSet<pms_Spare_Ship>();
            this.pms_SpareLib_File = new HashSet<pms_SpareLib_File>();
            this.pms_SpareLib_OldCopy = new HashSet<pms_SpareLib_OldCopy>();
            this.pms_Sparelib_InnerInfo = new HashSet<pms_Sparelib_InnerInfo>();
            this.pms_StoreItem = new HashSet<pms_StoreItem>();
            this.pms_TJob_Spare = new HashSet<pms_TJob_Spare>();
            this.pms_TObject_Spare = new HashSet<pms_TObject_Spare>();
            this.pms_TRepairListSpare = new HashSet<pms_TRepairListSpare>();
        }
    
        public int Id { get; set; }
        public string CatalogueNumber { get; set; }
        public string Name { get; set; }
        public string Parameters { get; set; }
        public int Unit { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<int> IdMCatalogSection { get; set; }
        public int IdChangeInfo { get; set; }
        public Nullable<int> IDLib { get; set; }
        public bool IsActive { get; set; }
        public string Ref1C { get; set; }
        public Nullable<int> IdManufacturerCatalog { get; set; }
        public bool IsCritical { get; set; }
        public Nullable<int> templdb_Code { get; set; }
        public Nullable<int> templdb_Version { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual pms_MaterialCatalogueSection pms_MaterialCatalogueSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Spare_Ship> pms_Spare_Ship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_SpareLib_File> pms_SpareLib_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_SpareLib_OldCopy> pms_SpareLib_OldCopy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Sparelib_InnerInfo> pms_Sparelib_InnerInfo { get; set; }
        public virtual pms_SpareManufacturerCatalog pms_SpareManufacturerCatalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_StoreItem> pms_StoreItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TJob_Spare> pms_TJob_Spare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TObject_Spare> pms_TObject_Spare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TRepairListSpare> pms_TRepairListSpare { get; set; }
    }
}
