//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_FileInfoManagedByShip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_FileInfoManagedByShip()
        {
            this.pms_JobHistoryRecord_File = new HashSet<pms_JobHistoryRecord_File>();
        }
    
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public Nullable<int> FileSize { get; set; }
        public int IdFile { get; set; }
        public Nullable<int> IdShip { get; set; }
        public string FileExtension { get; set; }
        public int IdChangeInfo { get; set; }
        public int IdChangeInfoFileData { get; set; }
        public Nullable<int> IDOuter { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual C_ChangeInfo C_ChangeInfo1 { get; set; }
        public virtual C_Ship C_Ship { get; set; }
        public virtual pms_FileManagedByShip pms_FileManagedByShip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobHistoryRecord_File> pms_JobHistoryRecord_File { get; set; }
    }
}
