//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_CounterLogRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_CounterLogRecord()
        {
            this.pms_Counter = new HashSet<pms_Counter>();
        }
    
        public int Id { get; set; }
        public System.DateTime ReadoutDate { get; set; }
        public int IdCounter { get; set; }
        public decimal Value { get; set; }
        public int IdChangeInfo { get; set; }
        public bool IsReset { get; set; }
        public Nullable<int> IDOuter { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Counter> pms_Counter { get; set; }
        public virtual pms_Counter pms_Counter1 { get; set; }
    }
}
