//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_FileLibInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_FileLibInfo()
        {
            this.pms_FileInfo_Ship = new HashSet<pms_FileInfo_Ship>();
            this.pms_TJob_File = new HashSet<pms_TJob_File>();
            this.pms_TObject_File = new HashSet<pms_TObject_File>();
            this.pms_SpareLib_File = new HashSet<pms_SpareLib_File>();
        }
    
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public Nullable<int> FileSize { get; set; }
        public int IdFile { get; set; }
        public int IdChangeInfo { get; set; }
        public string FileExtension { get; set; }
        public int IdChangeInfoFileData { get; set; }
        public Nullable<int> IDLib { get; set; }
        public string Ref1C { get; set; }
        public Nullable<int> templdb_Code { get; set; }
        public Nullable<int> templdb_Version { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual C_ChangeInfo C_ChangeInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_FileInfo_Ship> pms_FileInfo_Ship { get; set; }
        public virtual pms_FileLib pms_FileLib { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TJob_File> pms_TJob_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TObject_File> pms_TObject_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_SpareLib_File> pms_SpareLib_File { get; set; }
    }
}
