//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_TechPlace
    {
        public int Id { get; set; }
        public Nullable<int> ShipId { get; set; }
        public int IdObject { get; set; }
        public string Abb { get; set; }
        public string Type { get; set; }
        public string SupervisionOrg { get; set; }
        public string RegNumber { get; set; }
        public string RegRules { get; set; }
        public string Priority { get; set; }
        public string ExplState { get; set; }
        public string SubdivisionOwner { get; set; }
        public Nullable<int> IdRank { get; set; }
        public Nullable<int> IdPerson { get; set; }
        public string Owner { get; set; }
        public bool DispatcherJournal { get; set; }
        public string Room { get; set; }
        public string AddData1 { get; set; }
        public string AddData2 { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual C_Person C_Person { get; set; }
        public virtual C_Rank C_Rank { get; set; }
        public virtual C_Ship C_Ship { get; set; }
        public virtual pms_Object pms_Object { get; set; }
    }
}
