//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_TJobPeriod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_TJobPeriod()
        {
            this.pms_JobPeriod = new HashSet<pms_JobPeriod>();
        }
    
        public int Id { get; set; }
        public int IdTJob { get; set; }
        public Nullable<int> IdCounterType { get; set; }
        public Nullable<decimal> Period { get; set; }
        public Nullable<decimal> Notification { get; set; }
        public int IdChangeInfo { get; set; }
        public Nullable<int> Period_year { get; set; }
        public Nullable<int> Period_month { get; set; }
        public Nullable<int> Period_day { get; set; }
        public Nullable<int> Notification_year { get; set; }
        public Nullable<int> Notification_month { get; set; }
        public Nullable<int> Notification_day { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual pms_CounterType pms_CounterType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobPeriod> pms_JobPeriod { get; set; }
        public virtual pms_TJob pms_TJob { get; set; }
    }
}
