//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_TRepairList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_TRepairList()
        {
            this.pms_TRepairList_File = new HashSet<pms_TRepairList_File>();
            this.pms_TRepairListItem = new HashSet<pms_TRepairListItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdShipType { get; set; }
        public Nullable<int> IdShipProject { get; set; }
        public string Name { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual C_ShipProject C_ShipProject { get; set; }
        public virtual C_ShipType C_ShipType { get; set; }
        public virtual bdg_Currency bdg_Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TRepairList_File> pms_TRepairList_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TRepairListItem> pms_TRepairListItem { get; set; }
    }
}
