//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_StoreInventoryRecord
    {
        public int Id { get; set; }
        public int IdStoreItem { get; set; }
        public decimal Number { get; set; }
        public bool IsConsumption { get; set; }
        public string Note { get; set; }
        public Nullable<int> IdJobHistoryRecord { get; set; }
        public int IdChangeInfo { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> IdShip { get; set; }
        public Nullable<int> IdSpareOrderItem { get; set; }
        public Nullable<int> IdRank { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual C_Rank C_Rank { get; set; }
        public virtual C_Ship C_Ship { get; set; }
        public virtual pms_JobHistoryRecord pms_JobHistoryRecord { get; set; }
        public virtual pms_SpareOrderItem pms_SpareOrderItem { get; set; }
        public virtual pms_StoreItem pms_StoreItem { get; set; }
    }
}
