//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_Object_Counter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_Object_Counter()
        {
            this.pms_JobPeriod = new HashSet<pms_JobPeriod>();
        }
    
        public int Id { get; set; }
        public int IdObject { get; set; }
        public Nullable<int> IdCounter { get; set; }
        public int IdCounterType { get; set; }
        public int IdChangeInfo { get; set; }
        public Nullable<int> IDOuter { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual pms_Counter pms_Counter { get; set; }
        public virtual pms_CounterType pms_CounterType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobPeriod> pms_JobPeriod { get; set; }
        public virtual pms_Object pms_Object { get; set; }
    }
}
