//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_FileInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_FileInfo()
        {
            this.hseq_Inspection_File = new HashSet<hseq_Inspection_File>();
            this.hseq_Observation_File = new HashSet<hseq_Observation_File>();
            this.mrv_FuelOperation_File = new HashSet<mrv_FuelOperation_File>();
            this.pms_CompanySetting_LogoFile = new HashSet<pms_CompanySetting_LogoFile>();
            this.pms_FileDataExportInfo = new HashSet<pms_FileDataExportInfo>();
            this.pms_JobOrderItem_File = new HashSet<pms_JobOrderItem_File>();
            this.pms_RepairList_File = new HashSet<pms_RepairList_File>();
            this.pms_RepairListItem_File = new HashSet<pms_RepairListItem_File>();
            this.pms_RepairListSpare_File = new HashSet<pms_RepairListSpare_File>();
            this.pms_Requisition_File = new HashSet<pms_Requisition_File>();
            this.pms_SpareOrderItem_File = new HashSet<pms_SpareOrderItem_File>();
            this.pms_TRepairList_File = new HashSet<pms_TRepairList_File>();
            this.pms_TRepairListItem_File = new HashSet<pms_TRepairListItem_File>();
            this.pms_TRepairListSpare_File = new HashSet<pms_TRepairListSpare_File>();
            this.prs_PersonCard_File = new HashSet<prs_PersonCard_File>();
            this.prs_PersonCardPhoto = new HashSet<prs_PersonCardPhoto>();
            this.prs_PersonContract_File = new HashSet<prs_PersonContract_File>();
            this.prs_PersonDocument_File = new HashSet<prs_PersonDocument_File>();
        }
    
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public Nullable<int> FileSize { get; set; }
        public int IdFile { get; set; }
        public int IdChangeInfo { get; set; }
        public string FileExtension { get; set; }
        public int IdChangeInfoFileData { get; set; }
        public Nullable<int> IDOuter { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual C_ChangeInfo C_ChangeInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hseq_Inspection_File> hseq_Inspection_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hseq_Observation_File> hseq_Observation_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mrv_FuelOperation_File> mrv_FuelOperation_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_CompanySetting_LogoFile> pms_CompanySetting_LogoFile { get; set; }
        public virtual pms_File pms_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_FileDataExportInfo> pms_FileDataExportInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobOrderItem_File> pms_JobOrderItem_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RepairList_File> pms_RepairList_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RepairListItem_File> pms_RepairListItem_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RepairListSpare_File> pms_RepairListSpare_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Requisition_File> pms_Requisition_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_SpareOrderItem_File> pms_SpareOrderItem_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TRepairList_File> pms_TRepairList_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TRepairListItem_File> pms_TRepairListItem_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TRepairListSpare_File> pms_TRepairListSpare_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prs_PersonCard_File> prs_PersonCard_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prs_PersonCardPhoto> prs_PersonCardPhoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prs_PersonContract_File> prs_PersonContract_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prs_PersonDocument_File> prs_PersonDocument_File { get; set; }
    }
}
