//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_Object
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_Object()
        {
            this.pms_CodeTMK = new HashSet<pms_CodeTMK>();
            this.pms_Job = new HashSet<pms_Job>();
            this.pms_Object_File = new HashSet<pms_Object_File>();
            this.pms_Object_OldCopy = new HashSet<pms_Object_OldCopy>();
            this.pms_Object1 = new HashSet<pms_Object>();
            this.pms_Object_Counter = new HashSet<pms_Object_Counter>();
            this.pms_Object_Spare = new HashSet<pms_Object_Spare>();
            this.pms_OperatingTime = new HashSet<pms_OperatingTime>();
            this.pms_RepairListItem = new HashSet<pms_RepairListItem>();
            this.pms_SpareOrderItem = new HashSet<pms_SpareOrderItem>();
            this.pms_TechPlace = new HashSet<pms_TechPlace>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdParent { get; set; }
        public string Name { get; set; }
        public string Producer { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsCritical { get; set; }
        public Nullable<bool> IsSystem { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> IdPartition { get; set; }
        public Nullable<int> IdTObject { get; set; }
        public Nullable<int> IdTObjectSubLink { get; set; }
        public Nullable<int> IdShip { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
        public string Path { get; set; }
        public string ResultName { get; set; }
        public string CatalogueNumber { get; set; }
        public string ProductionYear { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual C_Ship C_Ship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_CodeTMK> pms_CodeTMK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Job> pms_Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Object_File> pms_Object_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Object_OldCopy> pms_Object_OldCopy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Object> pms_Object1 { get; set; }
        public virtual pms_Object pms_Object2 { get; set; }
        public virtual pms_Partition pms_Partition { get; set; }
        public virtual pms_TObject pms_TObject { get; set; }
        public virtual pms_TObject pms_TObject1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Object_Counter> pms_Object_Counter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Object_Spare> pms_Object_Spare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_OperatingTime> pms_OperatingTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_RepairListItem> pms_RepairListItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_SpareOrderItem> pms_SpareOrderItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TechPlace> pms_TechPlace { get; set; }
    }
}
