//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_Template
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_Template()
        {
            this.pms_TObject = new HashSet<pms_TObject>();
            this.pms_TObject1 = new HashSet<pms_TObject>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdTGroup { get; set; }
        public Nullable<int> templdb_Code { get; set; }
        public Nullable<int> templdb_Version { get; set; }
    
        public virtual pms_TGroup pms_TGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TObject> pms_TObject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TObject> pms_TObject1 { get; set; }
    }
}
