//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_JobReqApprovalStage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_JobReqApprovalStage()
        {
            this.pms_JobOrderItem_InnerInfo = new HashSet<pms_JobOrderItem_InnerInfo>();
            this.pms_JobReqApprovalStage1 = new HashSet<pms_JobReqApprovalStage>();
        }
    
        public int Id { get; set; }
        public int IdRequisitionRank { get; set; }
        public Nullable<int> IdParent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobOrderItem_InnerInfo> pms_JobOrderItem_InnerInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobReqApprovalStage> pms_JobReqApprovalStage1 { get; set; }
        public virtual pms_JobReqApprovalStage pms_JobReqApprovalStage2 { get; set; }
        public virtual pms_RequisitionRank pms_RequisitionRank { get; set; }
    }
}
