//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_Access
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public bool ShipCatalogueManage { get; set; }
        public bool TemplatesManage { get; set; }
        public bool AccessToAllPartitions { get; set; }
        public Nullable<int> IdPerson { get; set; }
        public bool PersonalManage { get; set; }
    
        public virtual C_Person C_Person { get; set; }
        public virtual C_User C_User { get; set; }
    }
}
