//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_JobPeriod_OldCopy
    {
        public int Id { get; set; }
        public int IdJobPeriod { get; set; }
        public Nullable<decimal> Period { get; set; }
        public Nullable<int> Period_year { get; set; }
        public Nullable<int> Period_month { get; set; }
        public Nullable<int> Period_day { get; set; }
        public Nullable<decimal> Notification { get; set; }
        public Nullable<int> Notification_year { get; set; }
        public Nullable<int> Notification_month { get; set; }
        public Nullable<int> Notification_day { get; set; }
    
        public virtual pms_JobPeriod pms_JobPeriod { get; set; }
    }
}
