//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_CompanySetting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_CompanySetting()
        {
            this.pms_CompanySetting_LogoFile = new HashSet<pms_CompanySetting_LogoFile>();
        }
    
        public int Id { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
        public bool IsHideFullPath { get; set; }
        public bool DisallowMinNumberOnShip { get; set; }
        public string AdditionalInfoForCrewListMAP { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_CompanySetting_LogoFile> pms_CompanySetting_LogoFile { get; set; }
    }
}
