//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_TObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_TObject()
        {
            this.pms_Object = new HashSet<pms_Object>();
            this.pms_Object1 = new HashSet<pms_Object>();
            this.pms_TJob = new HashSet<pms_TJob>();
            this.pms_TObject_File = new HashSet<pms_TObject_File>();
            this.pms_TObject1 = new HashSet<pms_TObject>();
            this.pms_TObject_Spare = new HashSet<pms_TObject_Spare>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdParent { get; set; }
        public string Name { get; set; }
        public string Producer { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsCritical { get; set; }
        public Nullable<bool> IsSystem { get; set; }
        public int IdTemplate { get; set; }
        public Nullable<int> IdSubTemplate { get; set; }
        public int IdChangeInfo { get; set; }
        public bool UsePostfix { get; set; }
        public Nullable<int> templdb_Code { get; set; }
        public Nullable<int> templdb_Version { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Object> pms_Object { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Object> pms_Object1 { get; set; }
        public virtual pms_Template pms_Template { get; set; }
        public virtual pms_Template pms_Template1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TJob> pms_TJob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TObject_File> pms_TObject_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TObject> pms_TObject1 { get; set; }
        public virtual pms_TObject pms_TObject2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TObject_Spare> pms_TObject_Spare { get; set; }
    }
}
