//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_TRepairListItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_TRepairListItem()
        {
            this.pms_TRepairListItem_File = new HashSet<pms_TRepairListItem_File>();
            this.pms_TRepairListItem1 = new HashSet<pms_TRepairListItem>();
            this.pms_TRepairListSpare = new HashSet<pms_TRepairListSpare>();
        }
    
        public int Id { get; set; }
        public int TRepairListId { get; set; }
        public int SortOrder { get; set; }
        public Nullable<int> ParentItemId { get; set; }
        public int TypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> MeasureUnitId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual pms_RepairListMeasureUnit pms_RepairListMeasureUnit { get; set; }
        public virtual pms_TRepairList pms_TRepairList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TRepairListItem_File> pms_TRepairListItem_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TRepairListItem> pms_TRepairListItem1 { get; set; }
        public virtual pms_TRepairListItem pms_TRepairListItem2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_TRepairListSpare> pms_TRepairListSpare { get; set; }
    }
}
