//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_JobHistoryCounterRecord
    {
        public int Id { get; set; }
        public int IdJobHistoryRecord { get; set; }
        public Nullable<int> IdCounter { get; set; }
        public Nullable<decimal> CounterValue { get; set; }
        public Nullable<System.DateTime> DateValue { get; set; }
        public Nullable<decimal> Period { get; set; }
        public Nullable<int> Period_year { get; set; }
        public Nullable<int> Period_month { get; set; }
        public Nullable<int> Period_day { get; set; }
        public Nullable<int> IdCounterType { get; set; }
        public Nullable<decimal> CounterValue_PostponedTo { get; set; }
        public Nullable<System.DateTime> DateValue_PostponedTo { get; set; }
        public Nullable<decimal> CounterValue_Plan { get; set; }
        public Nullable<System.DateTime> DateValue_Plan { get; set; }
        public Nullable<decimal> CounterValue_OnEnter { get; set; }
        public Nullable<System.DateTime> DateValue_OnEnter { get; set; }
    
        public virtual pms_Counter pms_Counter { get; set; }
        public virtual pms_CounterType pms_CounterType { get; set; }
        public virtual pms_JobHistoryRecord pms_JobHistoryRecord { get; set; }
    }
}
