//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_CodeTMK
    {
        public int Id { get; set; }
        public int IdObject { get; set; }
        public Nullable<int> ShipId { get; set; }
        public Nullable<int> IdShipOwner { get; set; }
        public string DirectionCode { get; set; }
        public Nullable<int> ShipTypeCode { get; set; }
        public string CodeSfi { get; set; }
        public string CodeSfiExtension { get; set; }
        public string SequenceNumberMechanism { get; set; }
        public string SequenceNumberUnit { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual C_Ship C_Ship { get; set; }
        public virtual pms_Object pms_Object { get; set; }
    }
}
