//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_Job()
        {
            this.pms_Job_File = new HashSet<pms_Job_File>();
            this.pms_Job_OldCopy = new HashSet<pms_Job_OldCopy>();
            this.pms_JobHistoryRecord1 = new HashSet<pms_JobHistoryRecord>();
            this.pms_JobOrderItem = new HashSet<pms_JobOrderItem>();
            this.pms_JobPeriod = new HashSet<pms_JobPeriod>();
            this.pms_JobPlan = new HashSet<pms_JobPlan>();
            this.pms_Job_Spare = new HashSet<pms_Job_Spare>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> IdResponsibleRank { get; set; }
        public Nullable<int> IdShip { get; set; }
        public string InstructionRef { get; set; }
        public string Instruction { get; set; }
        public string AdditionalInfo { get; set; }
        public string Note { get; set; }
        public Nullable<int> IdTJob { get; set; }
        public int IdObject { get; set; }
        public Nullable<int> NormPerformance { get; set; }
        public Nullable<int> IdJobType { get; set; }
        public Nullable<bool> IsOneTime { get; set; }
        public Nullable<bool> IsSupervised { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
        public bool IsStarted { get; set; }
        public Nullable<bool> IsInMonitoring { get; set; }
        public string ShortNameForMonitoring { get; set; }
        public Nullable<int> IdLastJobHistoryRecord { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual C_Rank C_Rank { get; set; }
        public virtual C_Ship C_Ship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Job_File> pms_Job_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Job_OldCopy> pms_Job_OldCopy { get; set; }
        public virtual pms_JobHistoryRecord pms_JobHistoryRecord { get; set; }
        public virtual pms_JobType pms_JobType { get; set; }
        public virtual pms_Object pms_Object { get; set; }
        public virtual pms_TJob pms_TJob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobHistoryRecord> pms_JobHistoryRecord1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobOrderItem> pms_JobOrderItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobPeriod> pms_JobPeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobPlan> pms_JobPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_Job_Spare> pms_Job_Spare { get; set; }
    }
}
