//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_ObjectCodePart
    {
        public int Id { get; set; }
        public int TypeId { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
        public string Name_en { get; set; }
    }
}
