//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_SpareOrderItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_SpareOrderItem()
        {
            this.pms_SpareOrderItem_File = new HashSet<pms_SpareOrderItem_File>();
            this.pms_SpareOrderItem_InnerInfo = new HashSet<pms_SpareOrderItem_InnerInfo>();
            this.pms_StoreInventoryRecord = new HashSet<pms_StoreInventoryRecord>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdSpare_Ship { get; set; }
        public string OtherSpareName { get; set; }
        public Nullable<int> OtherSpareUnit { get; set; }
        public Nullable<int> IdRequisition { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> IdRequisitionDepartment { get; set; }
        public decimal Number { get; set; }
        public Nullable<decimal> NumberConfirm { get; set; }
        public string Note { get; set; }
        public string CommentForShip { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
        public string Port { get; set; }
        public Nullable<int> IdObject { get; set; }
        public Nullable<decimal> NumberReceipt { get; set; }
        public Nullable<System.DateTime> DateReceipt { get; set; }
        public Nullable<int> IdOrderItemHistory { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual pms_Object pms_Object { get; set; }
        public virtual pms_OrderItemHistory pms_OrderItemHistory { get; set; }
        public virtual pms_Requisition pms_Requisition { get; set; }
        public virtual pms_RequisitionDepartment pms_RequisitionDepartment { get; set; }
        public virtual pms_Spare_Ship pms_Spare_Ship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_SpareOrderItem_File> pms_SpareOrderItem_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_SpareOrderItem_InnerInfo> pms_SpareOrderItem_InnerInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_StoreInventoryRecord> pms_StoreInventoryRecord { get; set; }
    }
}
