//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_JobOrderItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pms_JobOrderItem()
        {
            this.pms_JobOrderItem_File = new HashSet<pms_JobOrderItem_File>();
            this.pms_JobOrderItem_InnerInfo = new HashSet<pms_JobOrderItem_InnerInfo>();
            this.pms_JobPlan = new HashSet<pms_JobPlan>();
        }
    
        public int Id { get; set; }
        public int IdJob { get; set; }
        public Nullable<int> IdRequisition { get; set; }
        public Nullable<int> Status { get; set; }
        public decimal Number { get; set; }
        public Nullable<decimal> NumberConfirm { get; set; }
        public Nullable<decimal> NumberClosed { get; set; }
        public string Note { get; set; }
        public string CommentForShip { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
        public string Port { get; set; }
        public Nullable<int> IdOrderItemHistory { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual pms_Job pms_Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobOrderItem_File> pms_JobOrderItem_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobOrderItem_InnerInfo> pms_JobOrderItem_InnerInfo { get; set; }
        public virtual pms_OrderItemHistory pms_OrderItemHistory { get; set; }
        public virtual pms_Requisition pms_Requisition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pms_JobPlan> pms_JobPlan { get; set; }
    }
}
