//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_SpareOrderItem_InnerInfo
    {
        public int Id { get; set; }
        public int IdSpareOrderItem { get; set; }
        public int IdChangeInfo { get; set; }
        public string ProviderComment { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
        public string ReportComment_RU { get; set; }
        public string ReportComment_EN { get; set; }
        public Nullable<int> IdLastApprovementStage { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual pms_SpareOrderItem pms_SpareOrderItem { get; set; }
        public virtual pms_SpareReqApprovalStage pms_SpareReqApprovalStage { get; set; }
    }
}
