//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class pms_Object_Spare
    {
        public int Id { get; set; }
        public int IdObject { get; set; }
        public int IdSpare { get; set; }
        public Nullable<int> IdTObject_Spare { get; set; }
        public Nullable<decimal> RequiredNumber { get; set; }
        public Nullable<decimal> RequiredNumber_OldCopy { get; set; }
        public int IdChangeInfo { get; set; }
        public Nullable<int> IDOuter { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual pms_Object pms_Object { get; set; }
        public virtual pms_Spare_Ship pms_Spare_Ship { get; set; }
        public virtual pms_TObject_Spare pms_TObject_Spare { get; set; }
    }
}
