//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class prs_DocumentType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prs_DocumentType()
        {
            this.prs_CheckListItem = new HashSet<prs_CheckListItem>();
            this.prs_PersonDocument = new HashSet<prs_PersonDocument>();
        }
    
        public int Id { get; set; }
        public string Name_RU { get; set; }
        public string Name_EN { get; set; }
        public Nullable<int> Notification { get; set; }
        public int Partition { get; set; }
        public Nullable<int> SpecialType { get; set; }
        public bool IsShowInCrewListIMO { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prs_CheckListItem> prs_CheckListItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prs_PersonDocument> prs_PersonDocument { get; set; }
    }
}
