//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class prs_PersonDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prs_PersonDocument()
        {
            this.prs_PersonDocument_File = new HashSet<prs_PersonDocument_File>();
        }
    
        public int Id { get; set; }
        public int IdPersonCard { get; set; }
        public int IdDocumentType { get; set; }
        public string SeriesNumber { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string IssuePlace { get; set; }
        public Nullable<System.DateTime> ValidUntilDate { get; set; }
        public Nullable<int> IDOuter { get; set; }
        public int IdChangeInfo { get; set; }
    
        public virtual C_ChangeInfo C_ChangeInfo { get; set; }
        public virtual prs_DocumentType prs_DocumentType { get; set; }
        public virtual prs_PersonCard prs_PersonCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prs_PersonDocument_File> prs_PersonDocument_File { get; set; }
    }
}
