//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class prs_СrewСhangePlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prs_СrewСhangePlan()
        {
            this.prs_PersonContract = new HashSet<prs_PersonContract>();
        }
    
        public int Id { get; set; }
        public int IdShip { get; set; }
        public System.DateTime PlanDate { get; set; }
    
        public virtual C_Ship C_Ship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prs_PersonContract> prs_PersonContract { get; set; }
    }
}
